project:
  type: website
  output-dir: docs
  resources: 
    - "presentation-exercise/*.png"  # This forces Quarto to copy all PNGs in that folder

website:
  title: "My Portfoli-Joe: Joe Dainis's Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
          - text: "READY Exercise"
            file: ready-exercise/ready-exercise.html
          - text: "Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "CDC Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Presentation NHL Data Exercise"
            file: presentation-exercise/presentation-exercise.qmd
    right:
      - icon: github
        href: https://github.com/jdainis/JoeDainis-portfolio    
format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE